### ISSUE TITLE
Inconsistent external parameters in Proxy 

### ISSUE THREAD

**Issue by AntonAndell** [bandprotocol/band-std-reference-contracts-icon-java#3]
https://github.com/bandprotocol/band-std-reference-contracts-icon-java/blob/e6436868928e33c7f9faefd7feef0d77fa629529/std-reference-proxy/src/main/java/com/iconloop/score/oracle/StdReferenceProxy.java#L43

https://github.com/bandprotocol/band-std-reference-contracts-icon-java/blob/e6436868928e33c7f9faefd7feef0d77fa629529/std-reference-proxy/src/main/java/com/iconloop/score/oracle/StdReferenceProxy.java#L48

These two functions have different parameter names from the python contracts, which could break some integrations, mainly with frontends.

The python parameters are 
_base and _quote 

_bases and _quotes

**Comment by ajaya-man** [comment]
The data type for _bases and _quotes in get_reference_data_bulk also mismatch. In python contracts, they are of string data type while in Java they are of string array type.
