### ISSUE TITLE
Difference between forceRelay() and relay() method

### ISSUE THREAD

**Issue by ajaya-man** [bandprotocol/band-std-reference-contracts-icon-java#7]
What is the need for adding another forceRelay() method on top of relay() method ? We have been depending on the notion that the `resolve` times are always in increasing order. Adding resolve time previous to the current resolve time might create some issues in our application.

**Comment by warittornc** [comment]
forceRelay() is meant for emergencies or to delist certain symbols in the case where it isn't supported anymore. For example, if the price relayed or given timestamp for the price is erroneous this function can be used to override the current value.
